### ISSUE TITLE
Error on precompiled package for linux-64 - can't find ./httpsWorker.js

### ISSUE THREAD

**Issue by hpiedcoq** [GitSquared/sherlock-js#1]
Hello!

Thanks for this promising tool.
I downloaded the precompiled version for my ubuntu 64.

But I get this error. Npm is installed on my machine.

> [>] Input username: jfkennedy
internal/modules/cjs/loader.js:594
    throw err;
    ^

> Error:

 

> Cannot find module './httpsWorker.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
internal/modules/cjs/loader.js:594
    throw err;
    ^
 
Any idea?

**Comment by hpiedcoq** [comment]
OK solved.

The precompiled package HAS to be in the directory where the dependencies are.

So first clone the repo somewhere.
Download the precompiled package in this directory.
Do a chmod+x. 
Launch it.
